### ISSUE TITLE
Flashing might still work despite a "failed to detect ESP32 chip" message.

### ISSUE THREAD

**Issue by floitsch** [toitware/public#11]
As seen on https://stackoverflow.com/questions/68416663/failed-to-detect-esp32-chip-but-actually-found-and-worked

The failed to detect ESP32 chip message isn't always fatal. It might be worth adding a few lines of documentation. Just stating something like "Flashing might still work, do you want to continue?" would increase the likelihood of a successful flashing.

**Comment by marianopeck** [comment]
Thanks @floitsch 
Yes, I agree to soften a bit the message and still encourage people to give it a try.

**Comment by HelenaMeyer** [comment]
Fixed
