### ISSUE TITLE
Add 1-Wire protocol support

### ISSUE THREAD

**Issue by kasperl** [toitware/public#14]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use devices like DS18B20 that communicate via the 1-Wire protocol.

**Describe the solution you'd like**
It would be ideal if Toit would come with built-in support for the 1-Wire protocol, so it would be straightforward to attach and control a range of peripherals.

**Comment by floitsch** [comment]
Transferred to the toitlang organization.
