### ISSUE TITLE
Add driver package for DHT11/DHT22

### ISSUE THREAD

**Issue by kasperl** [toitware/public#16]
It would be very useful to be able to use the DHT11/DHT22 sensors from Toit code.

Inspiration: https://github.com/adafruit/DHT-sensor-library.

**Comment by xal88** [comment]
Would also vote for the One-wire driver.

Personally I do NOT recommend the use of the DHT/AM22x sensor family.  Gets broken in wet or dusty environment.
For a few cent more you can get the HTU21/Si7021 sensor with PTFE membrane cover.

A good comparison can be found here: [https://www.kandrsmith.org/RJS/Misc/Hygrometers/calib_many.html](https://www.kandrsmith.org/RJS/Misc/Hygrometers/calib_many.html)

**Comment by floitsch** [comment]
Moved this issue to the toitlang organization.
