### ISSUE TITLE
Update adc documentation with pin restrictions

### ISSUE THREAD

**Issue by davidg238** [toitware/public#17]
Adc is only supported on pins 32-39.

[Documentation](https://libs.toit.io/gpio/adc/library-summary) might be enhanced from:

`This library provides ways to read analogue voltage values from GPIO pins that support it.`

to:

`This library provides ways to read analogue voltage values from GPIO pins 32-39.`

Unknown if there are a firmware or board restrictions also?

**Comment by floitsch** [comment]
The documentation has been updated.
The changes will be reflected in the next release.
