### ISSUE TITLE
[BUG] Weather station tutorial fails on v1.3+ (BME280 driver)

### ISSUE THREAD

**Issue by kasperl** [toitware/public#23]
The weather station tutorial needs updating after the removal of the builtin BME280 driver.

https://docs.toit.io/platform/tutorials/starter/weatherstation

The code:
```
device := bus.device drivers.I2C_ADDRESS_ALT
```

leads to an unresolved identifier (I2C_ADDRESS_ALT) error.

**Comment by kasperl** [comment]
Looks like the conclusion was wrong. The BME280 driver has not been removed yet. 

The correct code is `drivers.Bme280.I2C_ADDRESS_ALT`. Should be a simple fix for the tutorial.

**Comment by jstroem** [comment]
Fix landed.
