### ISSUE TITLE
MQTT client subscribe does not handle "+" and "#" tokens

### ISSUE THREAD

**Issue by xal88** [toitware/public#26]
**Is your feature request related to a problem? Please describe.**
Have to read all ( maybe unknown ) topics from MQTT server under a specfic tree.  Currently wildcards are not interpreted, but simply treated as a topic name.

**Describe the solution you'd like** 
This is defined in the MQTT standard

``` 
Plus sign (+): 
It is a single level wildcard that matches any name for a specific topic level. 
We can use this wildcard instead of specifying a name for any topic level in the topic filter.
e.g. sensors/+/temperature

Hash (#): 
It is a multi level wildcard that we can use only at the end of the topic filter, as the last level 
and matches any topic whose first levels are the same as the topic levels specified at the left-hand side of the # symbol.
e.g. sensors/G0_BA1/#
```

**Describe alternatives you've considered**
Tried passing a list to the  current MQTT client ( 1.1.1) ,  (VSCode is complaining Type mismatch. Expected 'string'. Got 'List')

**Comment by andersjohnsen** [comment]
If I in one client says

```
  client.subscribe "a/#" --qos=1

  client.handle: | topic payload |
    print "$topic: $payload.to_string_non_throwing"
```

and in another says

```
  client.publish "a/b" "$it".to_byte_array
```

I get the data as expected. Perhaps you can provide a full example?

**Comment by xal88** [comment]
I can confirm that the  wildcard '#' is working as expected.
The wildcard '*'  goes to the topic name as the character '*' and is not interpreted as a wildcard.

If this is the planned behaviour, I can live with it - just have to filter the return topics accordingly.

**Comment by xal88** [comment]
I can confirm that the # wildcard and the + wildcard are working right.
Created new TOIT project in vsCode for testing now, and have updated my mosquitto on the openwrt inbetween.
Sorry for the confusion and thanks for your help

**Comment by andersjohnsen** [comment]
No problem, I'm glad we got it sorted out!
