### ISSUE TITLE
[docs] broken link in section about bootloader

### ISSUE THREAD

**Issue by ptxmac** [toitware/public#34]
**Describe the bug**
The page about 
[toubleshooting setup](https://docs.toit.io/support/troubleshoot/setuptroubleshoot) have a broken link to a page about bootloader mode (all of the official esp docs have been moved)

**To reproduce**
1. Go to https://docs.toit.io/support/troubleshoot/setuptroubleshoot
2. Click on "Read more info about the bootloader mode here."
3. Get broken link

**Expected behavior**
Correct link should be https://docs.espressif.com/projects/esptool/en/latest/esp32/troubleshooting.html#bootloader-won-t-respond (or something similar)

**Comment by floitsch** [comment]
Thanks!
The docs have been updated and the fix will be visible after the next deployment (hopefully soon).
