### ISSUE TITLE
ESP32-CAM

### ISSUE THREAD

**Issue by gazialankus** [toitware/public#36]
Do you have plans to support ESP32-CAMs? 

Some use cases I can think of

- [ ] Taking pictures and constantly uploading them
- [ ] Taking pictures and saving them locally in the microSD card, to be queried and downloaded remotely
- [ ] Videos
- [ ] Image processing (C bridge?)

**Comment by floitsch** [comment]
Migrated to https://github.com/toitlang/toit/issues/218
