### ISSUE TITLE
[BUG] BLE: Unresolved identifier: 'Device'

### ISSUE THREAD

**Issue by spro** [toitware/public#46]
I can't run the example from https://docs.toit.io/tutorials/ble/advertising, with the following error:

```
Running 'test-ble.toit' on 'ToitESP' ...
test-ble.toit:4:17: error: Unresolved identifier: 'Device'
  device := ble.Device.default
                ^~~~~~
Compilation failed.
```

Is the example code outdated?

**Comment by floitsch** [comment]
PR is under review: https://github.com/toitware/web-docs/pull/373

Thanks for reporting.

**Comment by floitsch** [comment]
The documentation has been updated.
(It might take a few minutes before the new code makes it through the pipeline).

**Comment by spro** [comment]
Works perfectly, cheers!
